### ISSUE TITLE
1.6.36 RL Release broke the plugin

### ISSUE THREAD

**Issue by PJVanRompaey** [AdrianLeeElder/runelite-bank-history-plugin#11]
https://github.com/AdrianLeeElder/runelite-bank-history-plugin/issues/10#issue-773298805

Would be a shame to see this plugin go.

**Comment by raywu2478** [comment]
damn that's why it's not on there anymore. Shame. I really liked this plugin

**Comment by MathieuDR** [comment]
Yeah! I loved it :)
It was a bit clunky, and not everything was working, but it was the only one who offered this functionality!

**Comment by AdrianLeeElder** [comment]
A fix has been merged into the runelite plugin repository.
