### ISSUE TITLE
Can't track Bank Tab 8+

### ISSUE THREAD

**Issue by Dracon27** [AdrianLeeElder/runelite-bank-history-plugin#2]
So, pretty simple issue, I have Bank Tabs 0-8 occupied in OSRS atm, however the plugin only allows tracking 0-7.  Would it be possible to expand the plugin to cover all the tabs?

**Comment by AdrianLeeElder** [comment]
Interesting, probably just a simple indexing issue. I will take a look when I get the chance. Thanks for reporting this!

**Comment by AdrianLeeElder** [comment]
The good news is we are currently tracking the bank value of tab 8, we just do not have the ability to select it to change the graph.

Pushing up a fix in a few minutes.
