### ISSUE TITLE
[FR] Hide login name

### ISSUE THREAD

**Issue by SieBrum** [AdrianLeeElder/runelite-bank-history-plugin#3]
Currently, the plugin uses the login username in the "select account" drop down box.

It would be cool for streamers, youtubers etc. to hide this name and give it an alias (check out the profile plugin, they use an alias and hide the username) so the username cannot be "seen". 

I understand that the username has to be saved in the background. But hiding it from the "visual" client would be a good feature

**Comment by AdrianLeeElder** [comment]
Thank you - that's a great suggestion. I will look into that.
