### ISSUE TITLE
Add an option to manually delete data entries

### ISSUE THREAD

**Issue by WaFFlzz** [AdrianLeeElder/runelite-bank-history-plugin#6]
![image](https://user-images.githubusercontent.com/65757799/87063168-fb84bb80-c1db-11ea-9345-06f807504440.png)
add an option maybe where you right click an entry like this that says "Delete Entry"

**Comment by chrstfer** [comment]
This is the same as issue #4. I recommend it be closed, @AdrianLeeElder. For the record, I'd love this feature as well.
