### ISSUE TITLE
Suggestion: Allow alias or use in-game name for username

### ISSUE THREAD

**Issue by KrisGlasier** [AdrianLeeElder/runelite-bank-history-plugin#7]
For those who either wish to hide the login-names involved with their accounts while streaming, screen sharing, or the overly cautious, I believe it would be nice to either add an alias to the usernames for each account or give the public display name for the accounts as their current in-game name.

**Comment by AdrianLeeElder** [comment]
This should be resolved - there's a checkbox to hide the username selection.
